version: '3'
services: 
  wildcat-pavilion:
    image: wildcat-pavilion-backend
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_NAME: wildcat_pavilion_dev
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: chack3349@
    ports:
      - "1337:1337"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: chack3349@
    volumes:
      - ./data:/var/lib/mysql
